[features]
seeds = false
[programs.localnet]
nuke = "HzwyTmrungBwbSmaBPPRo97iTC8Grqv7AQw297BGFsF2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/harshasomisetty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
